### ISSUE TITLE
fix for not sorting

### ISSUE THREAD

**Issue by narration-sd** [70kft/craft-help#1]
Hi - I've just started to use your craft-help, which looks very handy.

I found it wasn't sorting as suggested, by using 01-filename for example. Probably your native filesystem returns in alphameric-ascending naturally, but neither Win8.1 nor *nix on my host is doing so.

You can fix this easily looks like by adding a line with sort($data); just before return($data), about line 43 in services/Help_DocsService.php. 

sort() is apparently sufficient to do nested folders properly as well as top level, when I've tried it. I could go only one folder deep, as apparently that's a limit, probably a wise one for use.

**Comment by ktbartholomew** [comment]
@narration who's your nix host? I've ben struggling to find a provider where the sorting consistently doesn't work. So far the only one I've found is MediaTemple's (gs).

**Comment by ktbartholomew** [comment]
This is fixed with https://github.com/70kft/craft-help/commit/b2777d4005e2a0a2c2e613b04708b0023f0aeeac.

**Comment by narration-sd** [comment]
Hi Keith - in this case where the problem shows, it's asmallorange.com. I usually use Arcustech for anything important, but not at present; they're the cleanest and most reliable around. Presume you did find the issue showing on Windows - 8.1 up-to-date there.

Will have a look at your new version later today - good man ;)

**Comment by narration-sd** [comment]
And...appears to work fine.

Cheers, Keith
