### ISSUE TITLE
Just curious about the status on this plugin.

### ISSUE THREAD

**Issue by camelskyscraper** [70kft/craft-help#5]
I've been away from the website game for a while and am surprised to see this very useful plugin hasn't been updated in 2+ years. Do you use another option or is this one just still doing the job without a need to update the code?

**Comment by ktbartholomew** [comment]
The plugin was essentially created as an internal, open-sourced tool for 70kft, so @jpwdesigns would know whether people are actually using it or not. Other than that, nobody has requested any additional features or reported any significant bugs, so there's been no reason to change things 😄

**Comment by jpwdesigns** [comment]
@camelskyscraper what @ktbartholomew said is accurate. If you try it, let us know if you run into any problems.

**Comment by camelskyscraper** [comment]
Bravo! Thanks for the reply and the helpful plugin. (unintended pun)
